package hibernate;
// Generated 19-feb-2015 12:35:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set classesPermissions = new HashSet(0);

    public Classes() {
    }

    public Classes(String nombre, Set classesPermissions) {
       this.nombre = nombre;
       this.classesPermissions = classesPermissions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClassesPermissions() {
        return this.classesPermissions;
    }
    
    public void setClassesPermissions(Set classesPermissions) {
        this.classesPermissions = classesPermissions;
    }




}


